export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS_SUCCESS = "SET_INGREDIENTS_SUCCESS";
export const SET_INGREDIENTS_FAILED = "SET_INGREDIENTS_FAILED";

export const INIT_CHECKOUT = "INIT_CHECKOUT";
export const INIT_CONTACT_DATA = "INIT_CONTACT_DATA";
export const ORDER_CLICKED = "ORDER_CLICKED";
export const ORDER_HANDLED_SUCCESS = "ORDER_HANDLED_SUCCESS";
export const ORDER_HANDLED_FAILED = "ORDER_HANDLED_FAILED";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const SET_PAGE = "SET_PAGE";

export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
export const FETCH_ADDRESSES_FAILED = "FETCH_ADDRESSES_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILED = "AUTH_SIGNUP_FAILED";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const TOGGLE_AUTH_PAGE = "TOGGLE_AUTH_PAGE";
